<template>
  <main class="info-page"><header class="topbar"><router-link class="brand" to="/home-public"><span>智</span>智选优发</router-link><nav><router-link v-for="item in navItems" :key="item.path" :to="item.path" :class="{active:item.path===route.path}">{{ item.label }}</router-link></nav><button @click="router.push({path:'/home-public',query:{auth:'login'}})">登录</button></header><section class="hero"><p>{{ page.kicker }}</p><h1>{{ page.title }}</h1><span>{{ page.summary }}</span></section><section class="content-grid"><article v-for="item in page.items" :key="item.title"><component :is="item.icon" :size="23" /><h2>{{ item.title }}</h2><p>{{ item.copy }}</p></article></section><section class="back"><button @click="router.push('/home-public')"><ArrowLeft :size="17" />返回首页</button></section></main>
</template>
<script setup lang="ts">
import { computed } from 'vue'; import { useRoute,useRouter } from 'vue-router'; import { ArrowLeft,BookOpenCheck,FileSearch,Globe2,Headphones,ShieldCheck,Sparkles,UsersRound } from 'lucide-vue-next';
const route=useRoute(),router=useRouter(); const navItems=[{path:'/product-capabilities',label:'产品能力'},{path:'/solutions',label:'解决方案'},{path:'/rule-library',label:'规则库'},{path:'/customer-cases',label:'客户案例'},{path:'/help-center',label:'帮助中心'}];
const base={ '/product-capabilities':{kicker:'产品能力',title:'让每一份素材都有发布依据',summary:'把标题、卖点、图片与详情页纳入同一套发布前检查框架。',items:[['素材检查','定位文案、图片和详情页中的高频发布问题。',FileSearch],['规则匹配','按平台与市场组织发布要求。',ShieldCheck],['修改方向','提供适合目标市场的本地化修改方向。',Sparkles]]},'/solutions':{kicker:'解决方案',title:'把上架前的判断变成团队流程',summary:'适配运营、合规与品牌团队的协作方式。',items:[['新品上架','在首发前完成关键素材的集中检查。',FileSearch],['多平台发布','针对不同平台选择相应规则与市场语境。',Globe2],['团队复核','通过记录统一团队协作结论。',UsersRound]]},'/rule-library':{kicker:'规则库',title:'持续更新的发布规则',summary:'把平台规则、区域要求与发布表达放在一处管理。',items:[['平台规范','梳理主流跨境平台的商品与图片发布要求。',BookOpenCheck],['市场合规','识别不同地区的监管和表达要求。',ShieldCheck],['规则更新','为团队保留可追溯的规则变更记录。',Sparkles]]},'/customer-cases':{kicker:'客户案例',title:'从发布准备到团队协同',summary:'用结构化检查缩短每次发布前的沟通时间。',items:[['素材排查','快速定位标题、卖点与图片的发布准备项。',FileSearch],['本地化调整','以目标市场语境校准商品表达。',Globe2],['复核留痕','保留每次判断与修改建议的依据。',UsersRound]]},'/help-center':{kicker:'帮助中心',title:'让发布决策更容易开始',summary:'常见工作方式、素材范围和账号使用说明都在这里。',items:[['使用指南','按步骤准备商品素材。',BookOpenCheck],['账号支持','企业账号、角色和团队协作说明。',UsersRound],['联系支持','获取平台接入和使用建议。',Headphones]]}} as const;
const page=computed(()=>{const p=base[route.path as keyof typeof base]||base['/product-capabilities'];return {...p,items:p.items.map(([title,copy,icon])=>({title,copy,icon}))}});
</script>
<style scoped>
.info-page{min-height:100vh;background:#fbfaf8;color:#081837;font-family:"PingFang SC","Microsoft YaHei",sans-serif}.topbar{height:76px;padding:0 clamp(24px,6vw,88px);display:flex;align-items:center;border-bottom:1px solid #e5e7ed;gap:42px;background:#fff}.brand{color:#081837;text-decoration:none;font-size:21px;font-weight:800;display:flex;align-items:center;gap:9px}.brand span{display:grid;place-items:center;width:34px;height:34px;border-radius:8px;background:#1455db;color:#fff}.topbar nav{display:flex;gap:28px;margin-left:auto}.topbar nav a,.topbar>button{border:0;background:none;color:#33405a;text-decoration:none;cursor:pointer;font-weight:700}.topbar nav a.active,.topbar nav a:hover,.topbar>button:hover{color:#1455db}.hero{padding:92px 24px 70px;text-align:center;max-width:860px;margin:auto}.hero p{margin:0;color:#1455db;font-weight:750}.hero h1{font-size:clamp(42px,5.5vw,68px);letter-spacing:-.06em;line-height:1.13;margin:16px 0}.hero span{color:#5c6475;font-size:17px}.content-grid{max-width:1200px;margin:0 auto;padding:0 28px 88px;display:grid;grid-template-columns:repeat(3,1fr)}.content-grid article{padding:30px 34px;border-left:1px solid #dfe2e8}.content-grid article:first-child{border-left:0}.content-grid svg{color:#1455db}.content-grid h2{font-size:27px;margin:18px 0 10px}.content-grid p{color:#5c6475;line-height:1.8;min-height:78px}.back{text-align:center;padding-bottom:75px}.back button{border:1px solid #cbd4e5;background:#fff;color:#1455db;padding:14px 20px;display:inline-flex;align-items:center;gap:9px;font-weight:750;cursor:pointer}@media(max-width:760px){.topbar{padding:15px 20px;height:auto}.topbar nav{display:none}.topbar>button{margin-left:auto}.hero{padding:70px 24px 45px}.content-grid{grid-template-columns:1fr;padding:0 24px 60px}.content-grid article,.content-grid article:first-child{border:0;border-top:1px solid #dfe2e8;padding:28px 0}.content-grid article:first-child{border-top:0}}
</style>
